language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # PyPy2 2.5.0
  - "pypy-5.3.1"

install:
  - pip install zope.interface
  - pip install zope.lifecycleevent
  - pip install zope.component
  - pip install zope.deprecation
  - pip install https://github.com/bluedynamics/odict/archive/master.zip
  - pip install https://github.com/bluedynamics/plumber/archive/master.zip
  - pip install https://github.com/bluedynamics/node/archive/master.zip
  - python setup.py install

script: python -m unittest node.ext.directory.tests
